#------------------------
# Header config
title: 19900623@qq.com
author: add
logo_img: /img/Kaze.jpg # 将logo放入 ${blog_path}/source/img/${picname}.png 或使用url地址
author_img: /img/Kaze.jpg
author_description: designed by theme-kaze
#------------------------
# Navbar config
#------------------------
menus:
  home: /
  archive: /archives
  tags: /tags
  categories: /categories
  about: /about
  friends: /links
  # artitalk: /shuoshuo # You can uncomment to add this route

about:
  description: description
  social_links:
    # - { icon: icon, link: your link }

#------------------------
# Links
#------------------------
links:
  # name:
  #   url: https://example.com
  #   avatar:
  #   description:
  #------------------------
  # 提示：如果你想使用QQ头像但又不想泄露QQ号码，
  # 你可以使用这个API获取加密后的链接：
  # https://ptlogin2.qq.com/getface?appid=1006102&imgtype=3&uin=${yourQQNumber}
  # 然后将加密后的链接填入json中
  #------------------------

#------------------------
# Post
#------------------------
toc:
  showListNumber: false
  maxDepth: 6
  minDepth: 1

copyright:
  enable: true
  writer: # 如果作者为空，我们将使用 config.author 作为作者
  declare: 本博客所有文章除特别声明外，均采用<a target="_blank" rel="noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0 协议</a>。转载请注明出处！
  style: warning # 样式使用 note warning | danger | primary | info | success
#------------------------
# Footer
#------------------------
footer:
  copyYear: 2020
  # 如果 showPoweredBy 为 true，页脚将显示 'Powered by Hexo'
  showPoweredBy: true
  # 如果 showThemeName 为 true，页脚将显示 'Theme - Kaze'
  showThemeName: true
  #------------------------
  # Record config
  # 请将备案图片放入 ${yoursite}/img/beian.png
  RecordInfo: "" # 你的备案信息，例如 '某ICP备xxx号'
  govRecordInfo: "" # 你的公安备案信息，例如 '某公网安备xxx号'
  govRecordUrl: "" # 你的公安备案链接
  #------------------------
  # pv / uv 统计配置
  #------------------------
  statistics:
    enable: false
    type: busuanzi # 当前版本仅支持 busuanzi
    pv:
      enable: true
      style: 本站总访问量{}次 # 样式将显示为 $1{pv}$2
    uv:
      enable: true
      style: 本站总访客数{}次 # 样式将显示为 $1{uv}$2

#------------------------
# 动画配置
#------------------------
# 如果 scrollUpAnimation 为 true，将会有回到顶部的动画效果。
scrollUpAnimation: true

#------------------------
# 评论配置
#------------------------
comment:
  enable: false
  type: valine # valine | gitalk | livere | disqus | we recommend valine
  # gitalk 配置详情可见 https://github.com/gitalk/gitalk/blob/master/readme-cn.md
  valine:
    appId:
    appKey:
    placeholder: Just go go
    path: window.location.pathname
    avatar: mp
    meta: ["nick", "mail", "link"]
    pageSize: 10
    visitor: false
    highlight: true
    recordIP: false
    serverURLs: # leancloud国内自定义域名
    emojiCDN:
    emojiMaps: null
    enableQQ: false
    requiredFields: []
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.href
    distractionFreeMode: false
    # en | zh-CN | zh-TW
    language: navigator.language || navigator.userLanguage
  livere:
    uid:

#------------------------
# latex 配置
#------------------------
# 选择 true 以使用 mathjax 或 katex 渲染 latex
# 警告：latex 渲染会增加页面加载负担
latex:
  enable: false
  engine: mathjax # mathjax | katex
  # 为了获得更好的渲染效果，当你选择 mathjax 时，你可以直接使用它，但会失去一些效果
  # 所以你可以使用 hexo-renderer-kramed
  # 当你选择 katex 时，你必须使用 hexo-renderer-markdown-it-plus 或其他渲染引擎
  global: false
  # 当你选择 false 时，你可以通过在文章 Front-matter 中设置 `latex: true` 来使用 latex

#------------------------
# 懒加载配置
#------------------------
lazyload:
  enable: true
  loadingImg:

#------------------------
# 插件配置
#------------------------
fslightbox:
  enable: true
# 如果你的 hexo 版本低于 5.0.0，请先升级以使用此配置
# 我们支持八种高亮主题，你可以去 prism 网站 (https://prismjs.com) 获取更多信息
# theme: default | coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
prism:
  theme: tomorrow
# 显示文章字数统计
wordcount:
  enable: true
# Analytics config
analytics:
  enable: false
  type: google # google
  google:
    id: # 你可以在此处查看更多信息 https://analytics.google.com/
#------------------------
# 压缩配置
# css 压缩使用 autoprefixer 和 clean-css
# javascript 压缩使用 uglify-es
# html 压缩使用 html-minifier
#------------------------
minify:
  enable: false
  css: true
  js: true
  html: true
#------------------------
# 主题设计配置
#------------------------
# 主题颜色和样式的配置
# 你可以修改这些预设来设计不同的样式
color:
  text-color: "#3c4858"
  text-strong-color: "#2f3d4e"
  text-light-color: "#909faf"
  divider-color: "#e6e8ee"
  title-color: "#475b6d"
  link-color: "#3273dc"
  link-hover-color: "#6596e5"
  info-text-color: "#909faf"
  widget-background-color: "#fff"
  body-background-color: "#f2f5f8"
  border-color: "#e1e4e9"
  pre-color: "#2d2d2d"
  code-color: "#50687c"
  code-background-color: "#e9eaf0"

font:
  font-size: 16px # 全局字体大小
  font-family: '-apple-system,BlinkMacSystemFont,"Segoe UI","Helvetica Neue","PingFang SC","Microsoft YaHei",sans-serif' # 全局字体族

#------------------------
# cdn 配置
#------------------------
cdn:
  mathjax: //cdn.jsdelivr.net/npm/mathjax@3.0.5/es5/tex-svg.js
  katex: //cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
  gitalk:
    css: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
    js: //cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
  valine: //unpkg.com/valine/dist/Valine.min.js
  livere: //cdn-city.livere.com/js/embed.dist.js
  fslightbox: //cdn.jsdelivr.net/npm/fslightbox@3.1.0/index.min.js
  lozad: /js/lib/lozad.min.js
  prism: /js/lib/prism/
  busuanzi: /js/lib/busuanzi.min.js


